ALTER SESSION SET "_oracle_script" = TRUE;


-- Задание №1
CREATE TABLESPACE TS_TNA
DATAFILE 'D:\Study\DB\lab02\TS_TNA.dbf'
SIZE 7M
AUTOEXTEND ON NEXT 5M
MAXSIZE 30M
EXTENT MANAGEMENT LOCAL
;


-- Задание №2
CREATE TEMPORARY TABLESPACE TS_TNA_TEMP
TEMPFILE 'D:\Study\DB\lab02\TS_TNA_TEMP.dbf'
SIZE 5M
AUTOEXTEND ON NEXT 3M
MAXSIZE 20M
EXTENT MANAGEMENT LOCAL
;


-- Задание №3
SELECT TABLESPACE_NAME, STATUS, CONTENTS LOGGING FROM SYS.DBA_TABLESPACES;


-- Задание №4
SELECT TABLESPACE_NAME, STATUS, MAXBYTES, USER_BYTES, FILE_NAME FROM DBA_DATA_FILES
UNION
SELECT TABLESPACE_NAME, STATUS, MAXBYTES, USER_BYTES, FILE_NAME FROM DBA_TEMP_FILES
;


-- Задание №5
CREATE ROLE RL_TNACORE;

GRANT 
    CREATE SESSION,
    CREATE TABLE,
    CREATE VIEW,
    CREATE PROCEDURE
TO RL_TNACORE;


-- Задание №6
SELECT * FROM dba_roles WHERE ROLE LIKE 'RL%';


-- Задание №7
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'RL_TNACORE';


-- Задание №8
CREATE PROFILE PF_TNACORE LIMIT
PASSWORD_LIFE_TIME 180
SESSIONS_PER_USER 3
FAILED_LOGIN_ATTEMPTS 7
PASSWORD_LOCK_TIME 1
PASSWORD_REUSE_TIME 10
PASSWORD_GRACE_TIME DEFAULT
CONNECT_TIME 180
IDLE_TIME 30
;


-- Задание №9
SELECT DISTINCT PROFILE FROM DBA_PROFILES;


-- Задание №10
SELECT * FROM DBA_PROFILES WHERE PROFILE = 'PF_TNACORE';


-- Задание №11
SELECT * FROM DBA_PROFILES WHERE PROFILE = 'DEFAULT';


-- Задание №12
CREATE USER TNACORE IDENTIFIED BY 12345
DEFAULT TABLESPACE TS_TNA
TEMPORARY TABLESPACE TS_TNA_TEMP
PROFILE PF_TNACORE
ACCOUNT UNLOCK
PASSWORD EXPIRE
;

GRANT RL_TNACORE TO TNACORE;


-- Задание 16
ALTER USER TNACORE
QUOTA 2m ON TS_TNA;


-- Задание 18
ALTER TABLESPACE TS_TNA OFFLINE;


-- Задание №20
ALTER TABLESPACE TS_TNA ONLINE;


-- Очистка БД
DROP USER TNACORE CASCADE;
DROP PROFILE PF_TNACORE;
DROP ROLE RL_TNACORE;
DROP TABLESPACE TS_TNA_TEMP;
DROP TABLESPACE TS_TNA;
