-- Задание №1
SELECT * FROM SYS.DBA_TABLESPACES;


-- Задание №2
SELECT TABLESPACE_NAME, STATUS, FILE_NAME, USER_BYTES, MAXBYTES FROM DBA_DATA_FILES
UNION
SELECT TABLESPACE_NAME, STATUS, FILE_NAME, USER_BYTES, MAXBYTES FROM DBA_TEMP_FILES
;


-- Задание №3
SELECT * FROM V$LOG;


-- Задание №4
SELECT * FROM V$LOGFILE;


-- Задание №5
ALTER SYSTEM SWITCH LOGFILE;
SELECT * FROM V$LOG;


-- Задание №6
SELECT * FROM V$LOG;

ALTER DATABASE
ADD LOGFILE GROUP 4 'D:\Study\DB\lab04\REDO04.LOG'
    SIZE 50m
    BLOCKSIZE 512
;

ALTER DATABASE
ADD LOGFILE MEMBER 'D:\Study\DB\lab04\REDO041.LOG' TO GROUP 4
;

ALTER DATABASE
ADD LOGFILE MEMBER 'D:\Study\DB\lab04\REDO042.LOG' TO GROUP 4
;

ALTER SYSTEM SWITCH LOGFILE;
SELECT * FROM V$LOG;


-- Задание №7
ALTER DATABASE
DROP LOGFILE GROUP 4;


-- Задание №8 - 9
SELECT NAME, LOG_MODE FROM V$DATABASE;
SELECT INSTANCE_NAME, ARCHIVER, ACTIVE_STATE FROM V$INSTANCE;


-- Задание №10
-- shutdown immediate;
-- startup mount;
-- alter database archivelog;
-- alter database open;


-- Задание №11
ALTER SYSTEM SWITCH LOGFILE;
SELECT * FROM V$ARCHIVED_LOG;


-- Задание №12
-- shutdown immediate;
-- startup mount;
-- alter database noarchivelog;
-- alter database open;
SELECT NAME, LOG_MODE FROM V$DATABASE;
SELECT INSTANCE_NAME, ARCHIVER, ACTIVE_STATE FROM V$INSTANCE;


-- Задание №13-14
SELECT NAME FROM V$CONTROLFILE;

ALTER DATABASE BACKUP CONTROLFILE TO TRACE AS 'D:\Study\DB\lab04\CTL.txt' REUSE;
