-- (PDB, system)
CREATE TABLESPACE TS_PDB
DATAFILE 'D:\Study\DB\lab09\TS_PDB.dbf'
    SIZE 10m
    EXTENT MANAGEMENT LOCAL
;

CREATE TEMPORARY TABLESPACE TS_PDB_TEMP
TEMPFILE 'D:\Study\DB\lab09\TS_PDB_TEMP.dbf'
    SIZE 10m
    EXTENT MANAGEMENT LOCAL
;


CREATE ROLE RL_TNA;

GRANT
    CREATE SESSION,
    CREATE TABLE,
    CREATE SEQUENCE,
    CREATE CLUSTER,
    CREATE SYNONYM,
    CREATE PUBLIC SYNONYM,
    DROP PUBLIC SYNONYM,
    CREATE VIEW,
    CREATE MATERIALIZED VIEW,
    CREATE DATABASE LINK,
    CREATE PUBLIC DATABASE LINK
TO RL_TNA;


CREATE USER TNA
IDENTIFIED BY LabPDBUser
DEFAULT TABLESPACE TS_PDB
TEMPORARY TABLESPACE TS_PDB_TEMP
QUOTA UNLIMITED ON TS_PDB
ACCOUNT UNLOCK
;

GRANT RL_TNA TO TNA;
