-- Задание №1, 3
-- (CDB, Admin)
SELECT NAME, OPEN_MODE FROM v$pdbs;


-- Задание №4
-- (PDB, System)
CREATE TABLESPACE TS_TNA_PDB
DATAFILE 'D:\Study\DB\lab03\TS_TNA_PDB.dbf'
    SIZE 7M
    AUTOEXTEND ON NEXT 5M
    MAXSIZE 30M
    EXTENT MANAGEMENT LOCAL
;

CREATE TEMPORARY TABLESPACE TS_TNA_PDB_TEMP
TEMPFILE 'D:\Study\DB\lab03\TS_TNA_PDB_TEMP.dbf'
    SIZE 5M
    AUTOEXTEND ON NEXT 3M
    MAXSIZE 20M
    EXTENT MANAGEMENT LOCAL
;

CREATE ROLE RL_U1_TNA_PDB;

GRANT 
    CREATE SESSION,
    CREATE TABLE,
    CREATE VIEW,
    CREATE PROCEDURE
TO RL_U1_TNA_PDB;

CREATE PROFILE PF_U1_TNA_PDB LIMIT
PASSWORD_LIFE_TIME 180
SESSIONS_PER_USER 3
FAILED_LOGIN_ATTEMPTS 7
PASSWORD_LOCK_TIME 1
PASSWORD_REUSE_TIME 10
PASSWORD_GRACE_TIME DEFAULT
CONNECT_TIME 180
IDLE_TIME 30
;

CREATE USER U1_TNA_PDB IDENTIFIED BY U1TNAPDB
DEFAULT TABLESPACE TS_TNA_PDB
TEMPORARY TABLESPACE TS_TNA_PDB_TEMP
PROFILE PF_U1_TNA_PDB
ACCOUNT UNLOCK
;

GRANT RL_U1_TNA_PDB
TO U1_TNA_PDB;

ALTER USER U1_TNA_PDB
QUOTA 10m ON TS_TNA_PDB
;


-- Задание №5
-- (PDB, User)
CREATE TABLE TNA_TABLE (
    ID int
);

INSERT INTO TNA_TABLE(ID) VALUES (1);
INSERT INTO TNA_TABLE(ID) VALUES (2);

SELECT * FROM TNA_TABLE;


-- Задание №6
-- (PDB, Admin)
SELECT TABLESPACE_NAME, STATUS, MAXBYTES, USER_BYTES, FILE_NAME FROM DBA_DATA_FILES
UNION
SELECT TABLESPACE_NAME, STATUS, MAXBYTES, USER_BYTES, FILE_NAME FROM DBA_TEMP_FILES
;

SELECT GRANTEE, PRIVILEGE
FROM dba_roles INNER JOIN DBA_SYS_PRIVS ON dba_roles.ROLE = DBA_SYS_PRIVS.GRANTEE
;

SELECT DISTINCT PROFILE FROM DBA_PROFILES;

SELECT * FROM DBA_ROLE_PRIVS ORDER BY GRANTEE;


-- Задание №7
-- (CDB, Admin)
CREATE USER C##TNA IDENTIFIED BY Pa$$w0rd;
GRANT CREATE SESSION TO C##TNA;
-- (PDB, Admin)
GRANT CREATE SESSION TO C##TNA;


-- Задание №8
-- (PDB, Admin)
GRANT CREATE TABLE TO C##TNA;
ALTER USER C##TNA QUOTA UNLIMITED ON USERS;


-- Задание №10
-- (PDB, C##TNA)
CREATE TABLE C_TNA_TABLE (
    ID int
);
INSERT INTO C_TNA_TABLE VALUES (1);
INSERT INTO C_TNA_TABLE VALUES (2);
INSERT INTO C_TNA_TABLE VALUES (3);
SELECT * FROM C_TNA_TABLE;


-- Задание №11
-- (PDB, C##TNA, USER)
SELECT DISTINCT OBJECT_NAME FROM USER_OBJECTS;


-- Задание №12
-- (CDB, Admin)
CREATE USER C##LVO IDENTIFIED BY Pa$$w0rd;
GRANT CREATE SESSION TO C##LVO;
-- (PDB, Admin)
GRANT CREATE SESSION TO C##LVO;


-- Задание №13
-- (PDB, Admin)
SELECT 
    s.sid as "Sid", 
    s.serial# as "Serial#", 
    nvl(s.username, ' ') as "Username", 
    s.machine as "Machine", 
    s.schemaname as "Schema name", 
    s.logon_time as "Login time", 
    s.program as "Program", 
    s.osuser as "Os user", 
    s.status as "Status", 
    nvl(s.process, ' ') as "OS Process id"
FROM v$session s
WHERE username IS NOT NULL
ORDER BY 1,2;


-- Очистка БД
-- (PDB, Admin)
DROP USER U1_TNA_PDB CASCADE;
DROP PROFILE PF_U1_TNA_PDB;
DROP ROLE RL_U1_TNA_PDB;
DROP TABLESPACE TS_TNA_PDB_TEMP;
DROP TABLESPACE TS_TNA_PDB;
-- (CDB, Admin)
DROP USER C##TNA CASCADE;
DROP USER C##LVO CASCADE;
